<?php
/**
 * @file
 * Code for the OMBU Media feature.
 */

include_once 'ombumedia.features.inc';


/**
 * Hooks.
 */

/**
 * Implements hook_menu().
 */
function ombumedia_menu() {
  $items['admin/dashboard/manage-media'] = array(
    'title' => 'Manage Media',
    'type' => MENU_CALLBACK,
    'page callback' => 'ombumedia_page_magage_media',
    'access arguments' => array('administer files'),
    'file' => 'ombumedia.pages.inc',
  );

  $items['admin/dashboard/manage-media/ajax-upload'] = array(
    'type' => MENU_CALLBACK,
    'page callback' => 'ombumedia_page_magage_media_ajax_upload',
    'access arguments' => array('administer files'),
    'file' => 'ombumedia.pages.inc',
  );

  $items['file/%file/preview'] = array(
    'page callback' => 'ombumedia_page_file_preview',
    'page arguments' => array(1),
    'access callback' => 'file_entity_access',
    'access arguments' => array('view', 1),
    'file' => 'ombumedia.pages.inc',
  );

  return $items;
}

/**
 * Implements hook_theme().
 */
function ombumedia_theme($existing, $type, $theme, $path) {
  return array(
    'ombumedia_page' => array(
      'variables' => array(
        'media_library' => '',
        'mode' => 'manage',
      ),
      'template' => 'ombumedia_page',
    ),
    'ombumedia_file_preview' => array(
      'variables' => array(
        'file' => NULL,
      ),
      'template' => 'ombumedia_file_preview',
    ),
  );
}


/**
 * Preprocess.
 */

/**
 * Implements hook_preprocess_ombumedia_page().
 */
function ombumedia_preprocess_ombumedia_page(&$variables) {
  $path = drupal_get_path('module', 'ombumedia');
  drupal_add_js($path . '/js/ombumedia-util.js');
  drupal_add_js($path . '/js/ombumedia-library.js');
  drupal_add_css($path . '/css/ombumedia.css');

  $ombumedia_settings = array(
    'ombumedia' => array(
      'upload' => array(
        'url' => url('admin/dashboard/manage-media/ajax-upload'),
      ),
    ),
  );

  if ($variables['mode'] === 'manage') {
    drupal_add_js($path . '/js/init-manage.js');
  }

  drupal_add_js($ombumedia_settings, 'setting');
}

/**
 * Implements hook_preprocess_ombumedia_file_preview().
 */
function ombumedia_preprocess_ombumedia_file_preview(&$variables) {
  module_load_include('inc', 'file_entity', 'file_entity.pages');
  $file = $variables['file'];
  $variables['title'] = !empty($file->title) ? $file->title : $file->filename;
  $variables['preview'] = file_view_file($file, 'preview');
  $variables['usage'] = file_entity_usage_page($file);
}

/**
 * Implements hook_preprocess_views_view_unformatted().
 */
function ombumedia_preprocess_views_view_unformatted(&$variables) {
  if ($variables['view']->name === 'ombumedia') {
    $results = $variables['view']->result;
    foreach ($variables['rows'] as $i => $row) {
      $data_fid = 'data-fid="' . $results[$i]->fid . '"';
      $row = '<a href="#preview" ' . $data_fid . '>' . $row . '</a>';
      $row .= implode(' ', array(
        '<span class="actions">',
        '<a href="#select" ' . $data_fid . '>Select</a>',
        '<a href="#edit" ' . $data_fid . '>Edit</a>',
        '<a href="#delete" ' . $data_fid . '>Delete</a>',
        '</span>',
      ));
      $variables['rows'][$i] = $row;
      $variables['classes_array'][$i] .= ' ombumedia-library-file';
    }
  }
}
